USE [COMDATA]
GO

-- -------------------------------------------------------------------------------------
-- MODULO DE EVENTOS
-- -------------------------------------------------------------------------------------

-- -------------------------------------------------------------------------------------
-- [COMDATA_EVENTOS].[EVENTOS_ANO]
-- -------------------------------------------------------------------------------------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [COMDATA_EVENTOS].[EVENTOS_ANO](
	[ANO] [int] NOT NULL,
 CONSTRAINT [PK_EVENTOS_ANO] PRIMARY KEY CLUSTERED
(
	[ANO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

-- -------------------------------------------------------------------------------------
-- [COMDATA_EVENTOS].[EVENTOS_DIA_DA_SEMANA]
-- -------------------------------------------------------------------------------------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [COMDATA_EVENTOS].[EVENTOS_DIA_DA_SEMANA](
	[ID_DIA_DA_SEMANA] [int] NOT NULL,
	[DESCRICAO] [varchar](100) NOT NULL,
 CONSTRAINT [PK_EVENTOS_DIA_DA_SEMANA] PRIMARY KEY CLUSTERED
(
	[ID_DIA_DA_SEMANA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

-- -------------------------------------------------------------------------------------
-- [COMDATA_EVENTOS].[EVENTOS_ABRANGENCIA]
-- -------------------------------------------------------------------------------------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [COMDATA_EVENTOS].[EVENTOS_ABRANGENCIA](
	[ID_ABRANGENCIA] [int] NOT NULL,
	[DESCRICAO] [varchar](100) NOT NULL,
 CONSTRAINT [PK_EVENTOS_ABRANGENCIA] PRIMARY KEY CLUSTERED
(
	[ID_ABRANGENCIA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

-- -------------------------------------------------------------------------------------
-- [COMDATA_EVENTOS].[EVENTOS_PERIODO]
-- -------------------------------------------------------------------------------------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [COMDATA_EVENTOS].[EVENTOS_PERIODO](
	[ID_PERIODO] [int] NOT NULL,
	[DESCRICAO] [varchar](100) NOT NULL,
	[HORA_INICIO] [time](7) NULL,
	[HORA_FIM] [time](7) NULL,
 CONSTRAINT [PK_EVENTOS_PERIODO] PRIMARY KEY CLUSTERED
(
	[ID_PERIODO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

-- -------------------------------------------------------------------------------------
-- [COMDATA_EVENTOS].[EVENTOS_CATEGORIA]
-- -------------------------------------------------------------------------------------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [COMDATA_EVENTOS].[EVENTOS_CATEGORIA](
	[ID_CATEGORIA] [int] NOT NULL,
	[DESCRICAO] [varchar](100) NOT NULL,
 CONSTRAINT [PK_EVENTOS_CATEGORIA] PRIMARY KEY CLUSTERED
(
	[ID_CATEGORIA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

-- -------------------------------------------------------------------------------------
-- [COMDATA_EVENTOS].[EVENTOS_DETALHE]
-- -------------------------------------------------------------------------------------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [COMDATA_EVENTOS].[EVENTOS_DETALHE](
	[ID_DETALHE] [int] NOT NULL,
	[ID_CATEGORIA] [int] NOT NULL,
	[ID_ABRANGENCIA] [int] NOT NULL,
	[ID_PERIODO] [int] NOT NULL,
	[DESCRICAO] [varchar](100) NOT NULL,
	[INFO_ADICIONAL] [varchar](100) NULL,
 CONSTRAINT [PK_EVENTOS_DETALHE] PRIMARY KEY CLUSTERED
(
	[ID_DETALHE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

-- -------------------------------------------------------------------------------------
-- [COMDATA_EVENTOS].[EVENTOS_CALENDARIO]
-- -------------------------------------------------------------------------------------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [COMDATA_EVENTOS].[EVENTOS_CALENDARIO](
	[ID_CALENDARIO] [varchar](20) NOT NULL,
	[ID_DETALHE] [int] NOT NULL,
	[ID_DIA_DA_SEMANA] [int] NOT NULL,
	[ANO] [int] NOT NULL,
	[MES] [int] NOT NULL,
	[DIA] [int] NOT NULL,
	[DATA_EXTENSO] [datetime] NOT NULL,
	[DATA_INPUT] [datetime] NOT NULL,
 CONSTRAINT [PK_EVENTOS_CALENDARIO] PRIMARY KEY CLUSTERED
(
	[ID_CALENDARIO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_EVENTOS_CALENDARIO_DATA_1] ON [COMDATA_EVENTOS].[EVENTOS_CALENDARIO]
(
	[ANO] ASC,
	[MES] ASC,
	[DIA] ASC,
	[ID_DETALHE]
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_EVENTOS_CALENDARIO_DATA_2] ON [COMDATA_EVENTOS].[EVENTOS_CALENDARIO]
(
	[DATA_EXTENSO] ASC,
	[ID_DETALHE]
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
