/*
CHAMADA DA VIEW DE PESQUISA DE CALENDARIOS NO COMDATA_EVENTOS (EVENTOS)
*/

-- TUDO
Select
	A.*
From
	[COMDATA].[COMDATA_EVENTOS].[VW_EVENTOS_CALENDARIO_PESQUISAR] A
Where
	A.ANO = 2020
Order By
	A.DATA_EXTENSO;
